import type { TranscriptSegment } from './openai-realtime'
import type { CallSummary } from './summarizer'

export interface Attendee {
  name: string
  role?: string
}

export interface ShareableSummary {
  markdown: string
  attendees: Attendee[]
}

// Detect attendees from transcript and summary
export async function detectAttendees(
  segments: TranscriptSegment[],
  summary: CallSummary,
  apiKey: string
): Promise<Attendee[]> {
  const transcript = segments
    .filter(s => s.isFinal && s.text.trim())
    .map(s => s.text)
    .join('\n')

  const resp = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'gpt-4o',
      messages: [
        {
          role: 'system',
          content: `Identify all people mentioned by name in this call transcript and summary.
For each person, detect their role if mentioned (e.g., "Sarah from marketing", "John, the VP").
Return JSON: { "attendees": [{ "name": "Full Name", "role": "Role if known" }, ...] }
Only include people who actually participated in or were referenced in the call.
Do not include generic labels like "Speaker 1" — only actual names.`
        },
        {
          role: 'user',
          content: `Transcript:\n${transcript.substring(0, 3000)}\n\nSummary:\n${summary.overview}\nParticipants: ${summary.participants.join(', ')}`
        }
      ],
      response_format: { type: 'json_object' },
      temperature: 0.2
    })
  })

  if (!resp.ok) return summary.participants.map(p => ({ name: p }))

  const data = await resp.json() as { choices: Array<{ message: { content: string } }> }
  const content = data.choices[0]?.message?.content
  if (!content) return summary.participants.map(p => ({ name: p }))

  try {
    const parsed = JSON.parse(content)
    return Array.isArray(parsed.attendees) ? parsed.attendees : summary.participants.map(p => ({ name: p }))
  } catch {
    return summary.participants.map(p => ({ name: p }))
  }
}

// Generate the shareable meeting summary
export async function generateShareableSummary(
  segments: TranscriptSegment[],
  summary: CallSummary,
  attendees: Attendee[],
  sessionName: string | undefined,
  apiKey: string,
  skillContent?: string
): Promise<string> {
  const transcript = segments
    .filter(s => s.isFinal && s.text.trim())
    .map(s => s.text)
    .join('\n')

  const attendeeList = attendees.map(a => a.role ? `${a.name} (${a.role})` : a.name).join(', ')
  const date = new Date(summary.dateTime).toISOString().split('T')[0]

  const systemPrompt = `You are a professional meeting summary writer. Create a clean, shareable meeting summary suitable for distribution to all attendees.

${skillContent ? `Follow these formatting preferences:\n${skillContent}\n` : ''}

Format the summary as markdown with this structure:

## Meeting: ${sessionName || 'Call'} — ${date}

**Date:** ${date}
**Duration:** ${summary.durationMinutes} minutes
**Attendees:** ${attendeeList}

## Overview
(2-3 sentence professional summary)

## Key Discussion Points
(Main topics in clear bullet points, written for an external audience)

## Action Items

| Owner | Action | Due Date | Status |
|-------|--------|----------|--------|
(Every action item attributed to a specific person)

## Decisions Made
(Numbered list of decisions)

## Next Steps
(What happens after this meeting)

---
*Generated by Darkscribe*

Write in professional, neutral tone. No internal jargon. Every attendee should be able to read and understand this.`

  const resp = await fetch('https://api.openai.com/v1/chat/completions', {
    method: 'POST',
    headers: { 'Authorization': `Bearer ${apiKey}`, 'Content-Type': 'application/json' },
    body: JSON.stringify({
      model: 'gpt-4o',
      messages: [
        { role: 'system', content: systemPrompt },
        {
          role: 'user',
          content: `Create a shareable meeting summary from this data:\n\nTranscript:\n${transcript.substring(0, 4000)}\n\nInternal Summary:\nOverview: ${summary.overview}\nKey Topics: ${summary.keyTopics.join(', ')}\nAction Items: ${JSON.stringify(summary.actionItems)}\nDecisions: ${summary.decisions.join(', ')}\nFollow-ups: ${summary.followUps.join(', ')}`
        }
      ],
      temperature: 0.3
    })
  })

  if (!resp.ok) throw new Error(`API error: ${resp.status}`)

  const data = await resp.json() as { choices: Array<{ message: { content: string } }> }
  const content = data.choices[0]?.message?.content
  if (!content) throw new Error('Empty response')

  return content
}

// Build YAML frontmatter for the shareable summary file
export function buildShareableNoteFrontmatter(
  summary: CallSummary,
  attendees: Attendee[],
  sessionName?: string,
  internalNotePath?: string
): string {
  const date = new Date(summary.dateTime).toISOString().split('T')[0]
  return `---
tags: [meeting, shareable, summary]
date: "${date}"
contact: "${sessionName ?? ''}"
duration: "${summary.durationMinutes}min"
attendees: [${attendees.map(a => `"${a.name}"`).join(', ')}]
shared_with: []
---

`
}
